os: WMF 5
version: 1.{build}.0
install: 
    - ps: |
            Get-PackageProvider -Name NuGet -Force
            Install-Module -Name pester -RequiredVersion 3.3.5 -Verbose -Force
            Install-Module -Name xDSCResourceDesigner -Verbose -Force
            $Env:PSModulePath += (";" + (Resolve-Path .\DSCResources))

build: false

test_script:
    - ps: |
        $outputFile = Join-Path (Get-Location) "TestResults.xml"
        $result = Invoke-Pester .\Tests\*.tests.ps1 -OutputFormat NUnitXml -OutputFile $outputFile -PassThru
        Invoke-RestMethod -Uri "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)" -Method Post -InFile $outputFile -ContentType "application/json"
        if ($result.FailedCount -gt 0) { 
            throw "$($result.FailedCount) tests failed."
        }

deploy_script:
  - ps: |
        $path = Join-Path ${Env:APPVEYOR_BUILD_FOLDER} "${Env:APPVEYOR_PROJECT_NAME}.psd1"
        Update-ModuleManifest -Path $path -ModuleVersion ${Env:APPVEYOR_BUILD_VERSION}
        Publish-Module -Name ${Env:APPVEYOR_PROJECT_NAME} -Repository MyGet -NuGetApiKey ${Env:ACCESS_TOKEN} -Confirm:$false