os: WMF 5
version: 1.{build}.0
install: 
    - ps: |
            Get-PackageProvider -Name NuGet -Force
            Install-Module -Name pester -Force
            Install-Module -Name xDSCResourceDesigner -Force
build: false

test_script:
    - ps: |
        $result = Invoke-Pester .\Tests\*.tests.ps1 -OutputFormat NUnitXml -OutputFile  ".\TestsResults.xml" -PassThru
        Invoke-RestMethod -Uri "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)" -Method Post -InFile (Resolve-Path ".\TestResults.xml")
        if ($result.FailedCount -gt 0) { 
            throw "$($result.FailedCount) tests failed."
        }

deploy_script:
  - ps: |
        $path = Join-Path ${Env:APPVEYOR_BUILD_FOLDER} "${Env:APPVEYOR_PROJECT_NAME}.psd1"
        Update-ModuleManifest -Path $path -ModuleVersion ${Env:APPVEYOR_BUILD_VERSION}
        Publish-Module -Name ${Env:APPVEYOR_PROJECT_NAME} -Repository MyGet -NuGetApiKey ${Env:ACCESS_TOKEN} -Confirm:$false

notifications:        
- provider: Slack
  incoming_webhook:
    secure: doxpYXSV9U+Jb1vuaUOfeZiPu0KK5qgOERGa3l7aUo8BAjf8q6IMaA4SzwT8SvoeeOkS2JRQtN3XQ1lVhXbY+56TbmWsHAgKYKZlU2YpY5s=