os: WMF 5
version: 1.{build}.0
install: 
    - ps: |
            Get-PackageProvider -Name NuGet -Force
            Install-Module -Name pester -RequiredVersion 3.3.5 -Force
            Install-Module -Name xDSCResourceDesigner -Force
            Install-Module -Name PowerShellGet -RequiredVersion 1.0.0.1 -Force
            Import-Module -Name PowershellGet -RequiredVersion 1.0.0.1
            $Env:PSModulePath += (";" + (Resolve-Path .\DSCResources))

build: false

test_script:
    - ps: |
        $outputFile = Join-Path (Get-Location) "TestResults.xml"
        $result = Invoke-Pester -OutputFormat NUnitXml -OutputFile $outputFile -PassThru        
        (New-Object Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $outputFile)

deploy_script:
  - ps: |
        $path = Join-Path ${Env:APPVEYOR_BUILD_FOLDER} "${Env:APPVEYOR_PROJECT_NAME}.psd1"
        Update-ModuleManifest -Path $path -ModuleVersion ${Env:APPVEYOR_BUILD_VERSION}
        Publish-Module -Name ${Env:APPVEYOR_PROJECT_NAME} -Repository MyGet -NuGetApiKey ${Env:ACCESS_TOKEN} -Confirm:$false